#!/usr/bin/env node
// Pings IndexNow with URLs from site/sitemap.xml that are new or have a newer
// <lastmod> than the previous run. State file (tools/.indexnow-state.json) is
// committed so the diff is consistent across machines.
//
// Usage:
//   npm run indexnow            # diff + ping changed/new URLs
//   npm run indexnow -- --all   # ping every URL in the sitemap (use sparingly)
//   npm run indexnow -- --dry   # show what would be sent, don't POST

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SITE = path.join(ROOT, "site");
const CONFIG_PATH = path.join(ROOT, "tools", "indexnow.config.json");
const STATE_PATH = path.join(ROOT, "tools", ".indexnow-state.json");
const SITEMAP_PATH = path.join(SITE, "sitemap.xml");

const args = new Set(process.argv.slice(2));
const FORCE_ALL = args.has("--all");
const DRY_RUN = args.has("--dry");

function parseSitemap(xml) {
  // Sitemap is generated by us in builder/lib/sitemap.mjs — predictable shape,
  // no need for a real XML parser.
  const out = [];
  const re = /<url>([\s\S]*?)<\/url>/g;
  let m;
  while ((m = re.exec(xml)) !== null) {
    const block = m[1];
    const loc = (block.match(/<loc>([^<]+)<\/loc>/) || [])[1];
    const lastmod = (block.match(/<lastmod>([^<]+)<\/lastmod>/) || [])[1] || "";
    if (loc) out.push({ loc, lastmod });
  }
  return out;
}

async function main() {
  const cfg = JSON.parse(await fs.readFile(CONFIG_PATH, "utf8"));
  if (!cfg.key || !cfg.host) {
    throw new Error("indexnow.config.json must define `key` and `host`");
  }
  const endpoint = cfg.endpoint || "https://api.indexnow.org/indexnow";
  const keyLocation = `https://${cfg.host}/${cfg.key}.txt`;

  const sitemap = await fs.readFile(SITEMAP_PATH, "utf8").catch(() => {
    throw new Error(`sitemap not found at ${SITEMAP_PATH} — run \`npm run build\` first`);
  });
  const urls = parseSitemap(sitemap);
  if (!urls.length) throw new Error("sitemap parsed but contained no URLs");

  let state = {};
  try { state = JSON.parse(await fs.readFile(STATE_PATH, "utf8")); }
  catch (e) { if (e.code !== "ENOENT") throw e; }

  const changed = FORCE_ALL
    ? urls
    : urls.filter(u => !state[u.loc] || state[u.loc] !== u.lastmod);

  console.log(`sitemap: ${urls.length} URLs`);
  console.log(`changed: ${changed.length} URLs${FORCE_ALL ? " (--all)" : ""}`);

  if (!changed.length) {
    console.log("nothing to ping. exit.");
    return;
  }

  for (const u of changed.slice(0, 20)) console.log(`  + ${u.loc}`);
  if (changed.length > 20) console.log(`  … and ${changed.length - 20} more`);

  if (DRY_RUN) {
    console.log("\n--dry: not posting.");
    return;
  }

  const body = {
    host: cfg.host,
    key: cfg.key,
    keyLocation,
    urlList: changed.map(u => u.loc),
  };

  const res = await fetch(endpoint, {
    method: "POST",
    headers: { "Content-Type": "application/json; charset=utf-8" },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  console.log(`\nPOST ${endpoint} → ${res.status} ${res.statusText}`);
  if (text) console.log(text);

  if (res.status >= 200 && res.status < 300) {
    const next = {};
    for (const u of urls) next[u.loc] = u.lastmod;
    await fs.writeFile(STATE_PATH, JSON.stringify(next, null, 2) + "\n");
    console.log(`state updated: ${Object.keys(next).length} URLs tracked`);
  } else {
    process.exitCode = 1;
  }
}

main().catch(err => { console.error(err.message || err); process.exit(1); });
